#!/usr/bin/env python3
"""Refresh the social-share (Open Graph) meta tags in dashboard/index.html from data/latest.json.

LinkedIn, Facebook, Slack etc. do not run JavaScript, so the link preview can only show what is in
the static HTML. This writes the current score and band (in English) between the
<!-- meta:start --> and <!-- meta:end --> markers. build-single.py runs it first.

Usage: python3 dashboard/update-meta.py
"""
import html
import json
import pathlib
import re
import sys
from datetime import date

here = pathlib.Path(__file__).resolve().parent
index = here / "index.html"
latest = json.loads((here.parent / "data" / "latest.json").read_text(encoding="utf-8"))

# Absolute URL where og-image.png is uploaded next to the page (build-single.py copies it to dist/).
# Adjust if the page lives in a subfolder, e.g. https://tomologia.eu/ai-doomsday/og-image.png
IMAGE = "https://tomologia.eu/og-image.png"
IMAGE_ALT = ("AI Doomsday: a nuclear blast over a ruined skyline and a machine skull "
             "behind a fence, with a comet streaking across the sky")

score = latest["score"]
band = latest["band_en"]
change = latest.get("change_vs_previous")
d = date.fromisoformat(latest["date"])
as_of = f"{d.day} {d.strftime('%b %Y')}"
delta = f", {change:+d} vs previous report" if change else ""

title = f"AI Doomsday: {score}/1000 – {band}"
description = (f"AI bubble tension tracker, as of {as_of}: {score}/1000 ({band}{delta}). "
               "A daily AI-generated risk scale – not investment advice.")

tags = [
    ("property", "og:type", "website"),
    ("property", "og:site_name", "AI Doomsday"),
    ("property", "og:locale", "en_US"),
    ("property", "og:title", title),
    ("property", "og:description", description),
    ("property", "og:image", IMAGE),
    ("property", "og:image:width", "1200"),
    ("property", "og:image:height", "630"),
    ("property", "og:image:alt", IMAGE_ALT),
    ("name", "twitter:card", "summary_large_image"),
    ("name", "twitter:title", title),
    ("name", "twitter:description", description),
    ("name", "twitter:image", IMAGE),
]
block = "<!-- meta:start (generated by update-meta.py) -->\n" + "".join(
    f'  <meta {attr}="{key}" content="{html.escape(val, quote=True)}">\n' for attr, key, val in tags
) + "  <!-- meta:end -->"

src = index.read_text(encoding="utf-8")
new, n = re.subn(r"<!-- meta:start.*?<!-- meta:end -->", lambda _: block, src, flags=re.S)
if n != 1:
    sys.exit("expected exactly one meta:start … meta:end block in index.html")
if new != src:
    index.write_text(new, encoding="utf-8")
print(f"{title}\n{description}")
